### ISSUE TITLE
About the profile 

### ISSUE THREAD

**Issue by Hansmic** [long1eu/instagram_clone#3]
Thanks for doing wonderful projects for beginners like us to followed and understand, i have following your project for a while and have come to points really don't understand, 
Profile tap is giving error, thinking was I doing something wrong? 
2. It doesn't navigate to local library on your phone.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-09 at 10 06 08](https://user-images.githubusercontent.com/49045106/84178399-38249200-aa39-11ea-8f1b-7354ba839a58.png)

**Comment by Hansmic** [comment]
And also getting an error when signing in
```
flutter: error: 'package:instagram_clone/src/data/auth_api.dart': Failed assertion: line 107 pos 12: 'info != null': is not true.
flutter: stackTrace: #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      AuthApi._buildUser (package:instagram_clone/src/data/auth_api.dart:107:12)
<asynchronous suspension>
#3      AuthApi.login (package:instagram_clone/src/data/auth_api.dart:46:12)
<asynchronous suspension>
#4      AuthEpics._login.<anonymous closure> (package:instagram_clone/src/epics/auth_epics.dart:50:10)
#5      _FlatMapStreamSink.add (package:rxdart/src/transformers/flat_map.dart:16:33)
#6      forwardStream.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:34:49)
#7      forwardStream.runCatching (package:rxdart/src/utils/forwarding_stream.dart:24:12)
#8      forwardStream.<anonymous closure>.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:34:28)
#9      _rootRunUnary (dart:async/zone.dart:1192:38)
#10     _CustomZone.runUnary (dart:a<…>
flutter: LoginError {
  error='package:instagram_clone/src/data/auth_api.dart': Failed assertion: line 107 pos 12: 'info != null': is not true.,
}
```
